
spring:
  datasource:
    url: jdbc:mysql://demo-database:3306/demodb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: demouser
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      ddl-auto: update
      
  kafka:
    producer:
      bootstrap-servers: apache-kafka:9092
    consumer: 
      topic: customers
#      group-id: customers
      
      
#kafka:
#  topic: customers
#  port: 9092
#  host: apache-kafka