apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: customer-service
    version: v1
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
      version: v1
  template:
    metadata:
      labels:
        app: customer-service
        version: v1
    spec:
      containers:
      - env:
        - name: MYSQL_DB_USER
          value: demouser
        - name: MYSQL_DB_PASSWORD
          value: password
        - name: MYSQL_DB_HOST
          value: demo-database
        - name: MYSQL_DB_PORT
          value: "3306"
        image: docker.io/mrudul03/customer-service:29
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        name: customer-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false