---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  labels:
    app: customers-app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: customers-app
    tier: compute
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customers-service
  labels:
    app: customers-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: customers-app
        tier: compute
    spec:
      containers:
        - image: docker.io/mrudul03/customers-service:1
          imagePullPolicy: Always
          name: customers-service
          env:
            - name: MYSQL_DB_USER
              value: demouser
            - name: MYSQL_DB_PASSWORD
              value: password
            - name: MYSQL_DB_HOST
              value: demo-database
            - name: MYSQL_DB_PORT
              value: "3306"
          ports:
            - containerPort: 8080