---
apiVersion: v1
kind: Service
metadata:
  name: customer-composite-service
  labels:
    app: customer-composite-app
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: customer-composite-app
    tier: compute
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-composite-service
  labels:
    app: customer-composite-app
spec:
  strategy:
    type: Recreate
  
  template:
    metadata:
      labels:
        app: customer-composite-app
        tier: compute
    spec:
      containers:
        - image: docker.io/mrudul03/customer-composite-service:01
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - curl
              - localhost:8080/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          name: customer-composite-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - curl
              - localhost:8080/health
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1