#server:
#  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      ddl-auto: update
      
  kafka:
    producer:
      bootstrap-servers: apache-kafka:9092
    consumer: 
      topic: customers
#      group-id: customers
      
      
#kafka:
#  topic: customers
#  port: 9092
#  host: apache-kafka