
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/demodb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      ddl-auto: update
      
  kafka:
    consumer: 
      bootstrap-servers: apache-kafka:9092
      topic: customers
      group-id: customers
